include:
#  - ../docker/postgres/docker-compose.postgres.yml
  - path: supabase-docker/docker-compose.yml
    project_directory: supabase-docker/
    env_file: .env

services:
  app:
    build:
      context: ./app
    env_file:
      - .env
    ports:
      - ${DEV_VITE_PORT:-5173}:5173

    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

  mail:
    container_name: supabase-mail
    image: inbucket/inbucket:3.0.3
    ports:
      - '2500:2500' # SMTP
      - '9000:9000' # web interface
      - '1100:1100' # POP3
