services:
  y-sweet:
    restart: unless-stopped
    image: ghcr.io/jamsocket/y-sweet:latest
    command:
      "y-sweet serve /data --host 0.0.0.0 --auth AXO33rILFt0ZOP7v9NM8e2u6m1pVWvCS5HI9mYMK --url-prefix=http://y-sweet:9091/"
    volumes:
      - ./data:/data
    ports:
      - 9091:8080
